# Generated by Django 3.1.7 on 2021-02-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
