# Generated by Django 3.1.7 on 2021-02-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20210227_0319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceclass',
            unique_together={('date', 'status')},
        ),
    ]
