# Generated by Django 3.1.7 on 2021-02-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210301_0241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceclass',
            unique_together=set(),
        ),
    ]
