# Generated by Django 3.1.7 on 2021-03-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_attendance_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='subj',
            new_name='sub',
        ),
    ]
