# Generated by Django 3.1.7 on 2021-03-04 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20210304_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(choices=[('1', datetime.datetime(2021, 3, 5, 3, 5, 27, 199800)), ('2,', datetime.datetime(2021, 3, 5, 3, 5, 27, 199800))]),
        ),
    ]
