# Generated by Django 3.1.7 on 2021-06-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20210604_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'roll']},
        ),
    ]
